version: "2"
services:
  
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: --no-analytics 
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * SUN" --cleanup 
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host 
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ~/docker-configs/plex/config:/config
      - ~/storage/nas2/media:/mnt
    ports:
      - 32400:32400
    restart: unless-stopped
  sabnzbd: 
    image: linuxserver/sabnzbd
    container_name: sabnzbd 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ~/docker-configs/sabnzbd/config:/config
      - ~/storage/nas1/torrents/completed:/downloads
      - ~/storage/nas1/torrents/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: unless-stopped
  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ~/docker-configs/hydra2/config:/config
      - ~/storage/nas1/torrents:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ~/docker-configs/sonarr/config:/config
      - ~/storage/nas1/torrents/completed:/downloads
      - ~/storage/nas2/media/tv-shows:/tv
    ports:
      - 8989:8989 
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ~/docker-configs/radarr/config:/config
      - ~/storage/nas1/torrents/completed:/downloads
      - ~/storage/nas2/media/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped 
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ~/docker-configs/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
